FROM node:8.12.0-stretch

# set working directory
RUN mkdir -p /app
WORKDIR /app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN npm install -g @angular/cli@6.1.3 --unsafe

# install and cache app dependencies
COPY package.json /app
RUN npm install -f