FROM joseluis8906/restaurantetic-gui_base:1.0.0

# set working directory
WORKDIR /app

# install and cache app dependencies
COPY . /app

# build app
RUN npm run build:ssr

EXPOSE 4000

CMD npm run serve:ssr
